package org.see.skf.internal.callbacks;

import hla.rti1516_2025.*;
import hla.rti1516_2025.exceptions.*;
import hla.rti1516_2025.time.HLAinteger64Interval;
import hla.rti1516_2025.time.HLAinteger64Time;
import org.see.skf.internal.HLAUtilityFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Set;
import java.util.concurrent.*;

public final class HLACallbackManager {

    private static final Logger logger = LoggerFactory.getLogger(HLACallbackManager.class);

    private final RTIambassador rtiAmbassador;

    private final ExecutorService executor;

    // private final Set<NameReservationCallback> nameReservationCallbacks;
    private final Set<BiCallback<String, Boolean>> nameReservationCallbacks2;
    private final Set<ObjectInstanceHandle> instanceDiscoveryValueAcquisitionCallbacks2;
    // private final Set<InstanceDiscoveryValueAcquisitionCallback> instanceDiscoveryValueAcquisitionCallbacks;

    // private TimeConstrainedEnabledCallback timeConstrainedEnabledCallback;
    // private TimeRegulationEnabledCallback timeRegulationEnabledCallback;
    // private TimeAdvanceGrantCallback timeAdvanceGrantCallback;

    private Callback<HLAinteger64Time> timeConstrainedEnabledCallback;
    private Callback<HLAinteger64Time> timeRegulationEnabledCallback;
    private Callback<HLAinteger64Time> timeAdvanceGrantCallback;

    public HLACallbackManager(ExecutorService executor) {
        this.rtiAmbassador = HLAUtilityFactory.INSTANCE.getRtiAmbassador();
        this.executor = executor;

        this.nameReservationCallbacks2 = new CopyOnWriteArraySet<>();
        this.instanceDiscoveryValueAcquisitionCallbacks2 = new CopyOnWriteArraySet<>();

    }

    public Future<Boolean> invokeNameReservationCallback(String objectInstanceName) throws FederateNotExecutionMember, RestoreInProgress, IllegalName, NotConnected, RTIinternalError, SaveInProgress {
        BiCallback<String, Boolean> callback = new BiCallbackImpl<>(objectInstanceName,1);
        FutureTask<Boolean> task = callback.getTask();
        this.nameReservationCallbacks2.add(callback);
        this.executor.submit(task);

        rtiAmbassador.reserveObjectInstanceName(objectInstanceName);

        return task;
    }

    public void completeNameReservationCallback(String objectInstanceName, boolean outcomeValue) {
        for (BiCallback<String, Boolean> callback : this.nameReservationCallbacks2) {
            if (callback.getTarget().equals(objectInstanceName)) {
                callback.complete(outcomeValue);
                this.nameReservationCallbacks2.remove(callback);
            }
        }
    }

    // N.B. This method is purely for the case when an object instance is discovered, and we have no starting values to provide its
    // local representation in the federate. The actual update is done through the reflectAttributeValues callback in SKFederateAmbassador
    // but the Future returned here can at least block the thread until the initial values are received and we're ready to send out the
    // event generated by ObjectInstanceListener::created().
    public void invokeInstanceDiscoveryValueAcquisitionCallback(String instanceName, ObjectInstanceHandle instanceHandle, AttributeHandleSet subscribedAttributes) {
        this.instanceDiscoveryValueAcquisitionCallbacks2.add(instanceHandle);

        try {
            rtiAmbassador.requestAttributeValueUpdate(instanceHandle, subscribedAttributes, null);
        } catch (AttributeNotDefined | ObjectInstanceNotKnown | SaveInProgress | RestoreInProgress |
                 FederateNotExecutionMember | NotConnected | RTIinternalError e) {
            throw new RuntimeException("Failed to dispatch attribute value update request for the discovered object instance <" + instanceName + ">.", e);
        }
    }

    public boolean completeInstanceDiscoveryValueAcquisitionCallback(ObjectInstanceHandle targetHandle) {
        boolean completed = false;
        for (ObjectInstanceHandle handle  : this.instanceDiscoveryValueAcquisitionCallbacks2) {
            if (handle.equals(targetHandle)) {
                this.instanceDiscoveryValueAcquisitionCallbacks2.remove(handle);
                completed = true;
            }
        }

        return completed;
    }

    public Future<HLAinteger64Time> invokeTimeConstrainedCallback() throws FederateNotExecutionMember, RestoreInProgress, NotConnected, RTIinternalError, SaveInProgress {
        this.timeConstrainedEnabledCallback = new IAbstractCallbackImpl<>(1);
        FutureTask<HLAinteger64Time> task = this.timeConstrainedEnabledCallback.getTask();
        this.executor.submit(task);

        try {
            rtiAmbassador.enableTimeConstrained();
        } catch (InTimeAdvancingState | RequestForTimeConstrainedPending | TimeConstrainedAlreadyEnabled e) {
            logger.warn("Redundant attempt to time constrain this federate.", e);
        }

        return task;
    }

    public void completeTimeConstrainedCallback(HLAinteger64Time newLogicalTime) {
        if (this.timeConstrainedEnabledCallback != null) {
            this.timeConstrainedEnabledCallback.complete(newLogicalTime);
            this.timeConstrainedEnabledCallback = null;
        }
    }

    public Future<HLAinteger64Time> invokeTimeRegulationCallback(HLAinteger64Interval lookaheadInLogicalTime) throws FederateNotExecutionMember, RestoreInProgress, NotConnected, RTIinternalError, SaveInProgress {
        this.timeRegulationEnabledCallback = new IAbstractCallbackImpl<>(1);
        FutureTask<HLAinteger64Time> task = this.timeRegulationEnabledCallback.getTask();
        this.executor.submit(task);

        try {
            rtiAmbassador.enableTimeRegulation(lookaheadInLogicalTime);
        } catch (InTimeAdvancingState | RequestForTimeRegulationPending | TimeRegulationAlreadyEnabled e) {
            logger.warn("Redundant attempt to time regulate this federate.", e);
        } catch (InvalidLookahead e) {
            throw new RuntimeException(e);
        }

        return task;
    }

    public void completeTimeRegulationCallback(HLAinteger64Time newLogicalTime) {
        if (this.timeRegulationEnabledCallback != null) {
            this.timeRegulationEnabledCallback.complete(newLogicalTime);
            this.timeRegulationEnabledCallback = null;
        }
    }

    public Future<HLAinteger64Time> invokeTimeAdvanceGrantCallback(HLAinteger64Time nextLogicalTime) throws FederateNotExecutionMember, RestoreInProgress, NotConnected, RTIinternalError, SaveInProgress {
        this.timeAdvanceGrantCallback = new IAbstractCallbackImpl<>(1);
        FutureTask<HLAinteger64Time> task = this.timeAdvanceGrantCallback.getTask();
        this.executor.submit(task);

        try {
            rtiAmbassador.timeAdvanceRequest(nextLogicalTime);
        } catch (LogicalTimeAlreadyPassed | InvalidLogicalTime e) {
            throw new RuntimeException("Federate time is completely out of sync with the federation execution time.", e);
        } catch (InTimeAdvancingState | RequestForTimeRegulationPending | RequestForTimeConstrainedPending e) {
            logger.warn("Unsuccessful attempt to advance federate time.", e);
        }

        return task;

        /*
        this.timeAdvanceGrantCallback = new TimeAdvanceGrantCallback(null);
        FutureTask<HLAinteger64Time> task = this.timeAdvanceGrantCallback.getTask();
        this.executor.submit(task);

        try {
            rtiAmbassador.timeAdvanceRequest(nextLogicalTime);
        } catch (LogicalTimeAlreadyPassed | InvalidLogicalTime e) {
            throw new RuntimeException("Federate time is completely out of sync with the federation execution time.", e);
        } catch (InTimeAdvancingState | RequestForTimeRegulationPending | RequestForTimeConstrainedPending e) {
            logger.warn("Unsuccessful attempt to advance federate time.", e);
        }

        return task;
         */
    }

    public void completeTimeAdvanceGrantCallback(HLAinteger64Time grantedTime) {
        if (this.timeAdvanceGrantCallback != null) {
            this.timeAdvanceGrantCallback.complete(grantedTime);
            this.timeAdvanceGrantCallback = null;
        }
    }
}
